const { eventTypes } = require("./contracts");

module.exports = {
  RESOURCE_UPLOAD_REQUESTED: eventTypes.RESOURCE_UPLOAD_REQUESTED,
  RESOURCE_READY_FOR_STORAGE: eventTypes.RESOURCE_READY_FOR_STORAGE,
  RESOURCE_UPLOAD_COMPLETED: eventTypes.RESOURCE_UPLOAD_COMPLETED,
  RESOURCE_UPLOAD_FAILED: eventTypes.RESOURCE_UPLOAD_FAILED,
  RESOURCE_REENCRYPTION_REQUESTED: eventTypes.RESOURCE_REENCRYPTION_REQUESTED,
  RESOURCE_REENCRYPTION_COMPLETED: eventTypes.RESOURCE_REENCRYPTION_COMPLETED,
  RESOURCE_REENCRYPTION_FAILED: eventTypes.RESOURCE_REENCRYPTION_FAILED,
};